"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class JKU_t(object):
    __slots__ = ["utime", "num_data", "data"]

    def __init__(self):
        self.utime = 0.0
        self.num_data = 0
        self.data = []

    def encode(self):
        buf = BytesIO()
        buf.write(JKU_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fh", self.utime, self.num_data))
        buf.write(struct.pack('>%dd' % self.num_data, *self.data[:self.num_data]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != JKU_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return JKU_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = JKU_t()
        self.utime, self.num_data = struct.unpack(">fh", buf.read(6))
        self.data = struct.unpack('>%dd' % self.num_data, buf.read(self.num_data * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if JKU_t in parents: return 0
        tmphash = (0x809b9736b4d78115) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if JKU_t._packed_fingerprint is None:
            JKU_t._packed_fingerprint = struct.pack(">Q", JKU_t._get_hash_recursive([]))
        return JKU_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

